version: 0.0
os: linux
files:
  - source: /
    destination: /var/HelloWorld
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root

